Correcting an index error
I'm getting None and device_daily_stat is empty, perhaps due to old Firmware.  This error is throwed:
  File "/config/custom_components/neviweb130/light.py", line 363, in update
    self._today_energy_kwh_count = device_daily_stats[0]["counter"] / 1000
IndexError: list index out of range